[project]
name = "scrapper-gabriel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "pandas>=2.3.3",
    "ruff>=0.14.3",
    "watchdog>=6.0.0",
    "websockets>=15.0.1",
]
