---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scrapper-rolebinding-strimzi
  namespace: strimzi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scrapper-role-strimzi
subjects:
- kind: ServiceAccount
  name: scrapper-sa
  namespace: scrapper
